// Action names
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const CLEAR_DRAWER = 'CLEAR_DRAWER';

export const SET_INVESTORS = 'SET_INVESTORS';
export const SET_READ_INVESTORS = 'SET_READ_INVESTORS';
export const CLEAR_INVESTORS = 'CLEAR_INVESTORS';

export const SET_LOANS = 'SET_LOANS';
export const SET_READ_LOANS = 'SET_READ_LOANS';
export const CLEAR_LOANS = 'CLEAR_LOANS';

export const SELECT_PAGE = 'SELECT_PAGE';

export const SET_DATA_TABLE_DATA = 'SET_DATA_TABLE_DATA';
export const CLEAR_DATA_TABLE_DATA = 'CLEAR_DATA_TABLE_DATA';
