// Action names
export const SELECT_ENVIRONMENT = 'SELECT_ENVIRONMENT';
export const CLEAR_ENVIRONMENT = 'CLEAR_ENVIRONMENT';

export const SELECT_SBI = 'SELECT_SBI';
export const CLEAR_SBI = 'CLEAR_SBI';

export const SELECT_PLATFORM = 'SELECT_PLATFORM';
export const CLEAR_PLATFORM = 'CLEAR_PLATFORM';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_BRANCHES = 'SET_BRANCHES';
export const CLEAR_BRANCHES = 'CLEAR_BRANCHES';
export const SELECT_BRANCH = 'SELECT_BRANCH';
export const CLEAR_BRANCH = 'CLEAR_BRANCH';
